# Generated by Django 2.2.10 on 2020-03-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mediaDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('release_date', models.DateField()),
                ('rated', models.CharField(max_length=10)),
                ('runtime', models.DurationField()),
                ('genre', models.CharField(max_length=300)),
                ('director', models.CharField(max_length=255)),
                ('writers', models.TextField()),
                ('cast', models.TextField()),
                ('plot', models.TextField()),
                ('poster', models.ImageField(upload_to='movie_posters/')),
                ('backdrop', models.ImageField(upload_to='movie_posters/')),
                ('ratings_imdb', models.FloatField()),
                ('ratings_metacritic', models.FloatField()),
                ('ratings_rotten', models.FloatField()),
                ('ratings_average', models.FloatField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('favourite', models.BooleanField(default=False)),
                ('movie_path', models.CharField(max_length=400)),
            ],
        ),
    ]
