# Generated by Django 2.2.10 on 2020-03-14 12:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0002_auto_20200312_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediadatabase',
            name='movie_path',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage('C:\\Projects\\2020\\Binge\\Binge\\media/movie_storage/', '/media/movie_storage/'), upload_to=''),
        ),
    ]
