# Generated by Django 2.2.10 on 2020-03-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaserver', '0003_auto_20200314_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediadatabase',
            name='movie_path',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
